[package]
name = "dice-roller"
version = "2.1.1"
edition = "2024"

[profile.release]
codegen-units = 1
opt-level = "z"
lto = "fat"
panic = "abort"

[dependencies]
clap = { version = "4.5.45", features = ["derive"] }
rand = "0.9.2"
chrono = "0.4.41"
