[package]
name = "dice-roller"
version = "1.0.0"
edition = "2024"

[profile.release]
codegen-units = 1
opt-level = "z"
lto = "fat"
panic = "abort"

[dependencies]
chrono = "0.4.40"
clap = "4.5.32"
rand = "0.9.0"
