[package]
name = "dice-roller"
version = "2.0.0"
edition = "2024"

[profile.release]
codegen-units = 1
opt-level = "z"
lto = "fat"
panic = "abort"

[dependencies]
clap = { version = "4.5.35", features = ["derive"] }
rand = "0.9.0"
chrono = "0.4.40"
